config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  

  resources :stories

  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
 end

 # /@tinayu/title-123
 get '@:username/:story_id', to: 'pages#show', as: 'story_page'

 # /@tinayu/
 get '@:username', to: 'pages#user', as: 'user_page'

   
  # Defines the root path route ("/")
   root "pages#index"
end

app/views/shared/frontend/_flash.html.erb
<div class="notification is-success">
  <%= notice %>
</div>

app/views/shared/frontend/_navbar.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
  <%= link_to root_path, class: "navbar-item" do%>
      <img src="/clock.png" width="28" height="28">
      <p class="nownow">Now</p>
    </a>
    <% end %>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  


  <div id="navbarBasicExample" class="navbar-menu">
   
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">

        <%if user_signed_in? %>
        
        <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
        <%= avatar(current_user, size: 50) %>
          <%= current_user.email %>
        </a>

        <div class="navbar-dropdown">
        <%= link_to "New Stories", new_story_path, class:'navbar-item' %>
        <%= link_to "Story Series", stories_path, class:'navbar-item' %>
        <hr class="navbar-divider">
        <%= link_to "Profile", edit_user_registration_path, class:'navbar-item' %>
          <hr class="navbar-divider">
        <%= link_to "Sign Out", destroy_user_session_path, class:'navbar-item', method: 'delete', data: {confirm: 'do you want to sign out?'} %>
          
        </div>
        
        <%else%>
        <%= link_to "Sign up", new_user_registration_path, class:'button is-primary' %>
        <%= link_to "Log in", new_user_session_path, class:'button is-light' %>
          
         
          <%end%>
        </div>
      </div>
    </div>
  </div>
</nav>