config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  

  resources :stories

  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
 end

 # /@tinayu/title-123
 get '@:username/:story_id', to: 'pages#show', as: 'story_page'

 # /@tinayu/
 get '@:username', to: 'pages#user', as: 'user_page'

   
  # Defines the root path route ("/")
   root "pages#index"
end

app/views/pages/index.html.erb
      <div>
       <br/>
       <hr>
        <br/>
          
      </div>
      
      <section class="columns all-articles" >
       
        <!-- article list -->
        <section class="column is-two-thirds">
        <% @stories.each do |story| %>
          <article class="media">
            <div class="media-content">
              <h2 class="title is-4"><%= link_to story.title, story_page_path(story.user.username, story), class: 'has-text-grey-dark' %></h2>
              <p class="content"><%= strip_tags(story.content).truncate(200) %></p>
              <footer>
                <p> <%= link_to story.user.username, user_page_path(story.user.username), class: 'has-text-grey-dark' %> | <%= time_ago_in_words(story.created_at) %>
            </p>
              </footer>
            </div>
           <% if story.cover_image.attached? %>
            <figure class="media-right">
              <%= image_tag story.cover_image.variant(resize_to_limit: [150,150]) %>
            </figure>
            <% end %>

          </article>
          <% end %>

        </section>
        <!-- article list -->

    
      </section>

app/views/pages/show.html.erb
<section class="columns has-text-centered story-content">
  <section class="column is-offset-3 is-6">
    <h1 class="title"><%= @story.title %></h1>

    <span class="profile" data-controller="user">
      <%= image_tag @story.user.avatar.variant(resize_to_fit: [50,50]), class: 'avatar' if @story.user.avatar.attached? %>
      <span class="username"><%= @story.user.username %></span>
     
    
    </span>

    <article class="content">
      <%= image_tag @story.cover_image.variant(resize_to_limit: [1000,500]), class: 'cover-image' if @story.cover_image.attached? %>
      <%= @story.content.html_safe %>

      
      
    </article>
    <hr>
  
  </section>
</section>